apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: cassandra
spec:
  endOfLife:
    identifier: apache-cassandra
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  lastUpdatedTimestamp: "2023-12-14T21:09:19.808404692Z"
  latestVersion: 4.1.3
  versions:
  - releaseDate: "2022-12-13"
    version: "4.1"
  - releaseDate: "2021-07-26"
    version: "4.0"
  - releaseDate: "2017-06-23"
    version: "3.11"
  - releaseDate: "2015-11-09"
    version: "3.0"
