apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: haproxy
spec:
  endOfLife:
    identifier: haproxy
  versionStreamFormat: ${{name}}-${{versions.major}}.${{versions.minor}}
status:
  eolVersions:
  - eolDate: "2023-02-14"
    releaseDate: "2021-11-23"
    version: "2.5"
  - eolDate: "2022-01-01"
    releaseDate: "2020-11-05"
    version: "2.3"
  - eolDate: "2021-03-18"
    releaseDate: "2019-11-25"
    version: "2.1"
  - eolDate: "2020-07-31"
    releaseDate: "2018-12-19"
    version: "1.9"
  - eolDate: "2022-10-01"
    releaseDate: "2017-11-26"
    version: "1.8"
  - eolDate: "2021-10-01"
    releaseDate: "2016-11-25"
    version: "1.7"
  lastUpdatedTimestamp: "2023-12-15T00:13:49.568787303Z"
  latestVersion: 2.9.0
  versions:
  - releaseDate: "2023-12-05"
    version: "2.9"
  - lts: "true"
    releaseDate: "2023-05-31"
    version: "2.8"
  - releaseDate: "2022-12-01"
    version: "2.7"
  - lts: "true"
    releaseDate: "2022-05-31"
    version: "2.6"
  - lts: "true"
    releaseDate: "2021-05-14"
    version: "2.4"
  - lts: "true"
    releaseDate: "2020-07-07"
    version: "2.2"
  - releaseDate: "2019-06-16"
    version: "2.0"
