apiVersion: versions.wolfi.dev/v1
kind: VersionStream
metadata:
  name: openjdk
spec:
  endOfLife:
    identifier: redhat-build-of-openjdk
  versionStreamFormat: ${{name}}-${{versions.major}}
status:
  eolVersions:
  - eolDate: "2020-06-30"
    releaseDate: "2013-01-07"
    version: "7"
  - eolDate: "2016-12-31"
    releaseDate: "2009-01-20"
    version: "6"
  lastUpdatedTimestamp: "2023-12-19T07:30:31.882940587Z"
  latestVersion: 17.0.9.0.9-1
  versions:
  - eolDate: "2027-10-30"
    releaseDate: "2021-05-18"
    version: "17"
  - eolDate: "2024-10-30"
    releaseDate: "2018-10-30"
    version: "11"
  - eolDate: "2026-11-30"
    releaseDate: "2015-03-05"
    version: "8"
